FROM ubuntu:16.04
FROM python:3.7
RUN apt-get update -y
# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./static /app/static
# COPY ./memes_images /app/memes_images
COPY ./results /app/results
COPY ./app.py /app/app.py

CMD ["python", "app.py"]